### PR TITLE
Exposing service inside gpd_node to set the workspace, workspace_grasp, and camera_position parameters

### PR DESCRIPTION
**Pull request by jaymwong**
Adding a feature to allow external nodes to dynamically change the `workspace`, `workspace_grasps`, and `camera_position` parameters within the `grasp_detection_node`.

### CODE REVIEW

**Comment by tanay-bits** [comment]
Thanks for this! I have a few small questions. What's the difference between `workspace` and `workspace_grasps`? Also, how does changing `camera_position` affect how the workspace is interpreted? As I understand, the default [0, 0, 0] means the camera's frame is the origin of the coordinates in which workspace is defined. If I change it to the [x, y, z] of the camera frame relative to my robot's base frame, would the workspace be now defined with respect to this base frame?

**Comment by tanay-bits** [comment]
Thanks for your explanation! If I want to detect grasps on objects in a region of interest (say, a 3D bounding box), is there a difference between
(a) Using this service to constrain the workspace to the region of interest (while still using the raw PointCloud2 as the input to the GPD node), and
(b) Creating a CloudSampled or CloudIndexed or SamplesMsg message from the region of interest, and passing that to GPD (while having a large enough workspace to cover the entire point cloud)?

If option (b) simply crops the input cloud to the samples or indices we provide, I'm assuming it would have the problem of useless grasps being generated at the boundaries of that cropped region?

**Comment by atenpas** [comment]
Using workspace parameters is different from using samples/indices. The _complete_ point cloud should always be passed to GPD so that it can be used to check the grasps against collisions (e.g., collisions with a tabletop). 

The `workspace` parameter cuts the point cloud. So, if you cut out the table plane, you might have grasps that approach an object from below the table. 

Using a `CloudSamples/CloudIndexed` message is the ideal way to go. In this way, you can provide the complete point cloud (potentially downsampled/voxelized) for collision checking, and use the samples/indices to focus where to look for grasps and for speed up.

**Comment by tanay-bits** [comment]
Thank you! Using `CloudSamples` produced much better results for me.

**Pull request merged**
